# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat_message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat_message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x63hat_message.proto\"\xa7\x01\n\x0f\x43hatRoomRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x31\n\tuser_list\x18\x04 \x03(\x0b\x32\x1e.ChatRoomRequest.UserListEntry\x1a/\n\rUserListEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3'
)




_CHATROOMREQUEST_USERLISTENTRY = _descriptor.Descriptor(
  name='UserListEntry',
  full_name='ChatRoomRequest.UserListEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ChatRoomRequest.UserListEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='ChatRoomRequest.UserListEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=190,
)

_CHATROOMREQUEST = _descriptor.Descriptor(
  name='ChatRoomRequest',
  full_name='ChatRoomRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ChatRoomRequest.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_name', full_name='ChatRoomRequest.user_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='ChatRoomRequest.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_list', full_name='ChatRoomRequest.user_list', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CHATROOMREQUEST_USERLISTENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=190,
)

_CHATROOMREQUEST_USERLISTENTRY.containing_type = _CHATROOMREQUEST
_CHATROOMREQUEST.fields_by_name['user_list'].message_type = _CHATROOMREQUEST_USERLISTENTRY
DESCRIPTOR.message_types_by_name['ChatRoomRequest'] = _CHATROOMREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChatRoomRequest = _reflection.GeneratedProtocolMessageType('ChatRoomRequest', (_message.Message,), {

  'UserListEntry' : _reflection.GeneratedProtocolMessageType('UserListEntry', (_message.Message,), {
    'DESCRIPTOR' : _CHATROOMREQUEST_USERLISTENTRY,
    '__module__' : 'chat_message_pb2'
    # @@protoc_insertion_point(class_scope:ChatRoomRequest.UserListEntry)
    })
  ,
  'DESCRIPTOR' : _CHATROOMREQUEST,
  '__module__' : 'chat_message_pb2'
  # @@protoc_insertion_point(class_scope:ChatRoomRequest)
  })
_sym_db.RegisterMessage(ChatRoomRequest)
_sym_db.RegisterMessage(ChatRoomRequest.UserListEntry)


_CHATROOMREQUEST_USERLISTENTRY._options = None
# @@protoc_insertion_point(module_scope)
